test:  
  override:
    - "true"

dependencies:
  post:
    - bundle exec jekyll build

deployment:
  production:
    branch: master
    commands:
      - scp -r * rafaelgeronimo@rafaelgeronimo.com:/rafaelgeronimo.com/